// react-reference/src/components/hitl/LoyaltyRewardCard.tsx
import { LoyaltyRewardPreview } from '../../types/hitl-previews'
import { HITLCardProps, HITLCardWrapper, formatPrice } from './HITLCard'
import { FoodicsIcon } from '../ui/FoodicsIcon'

export function LoyaltyRewardCard({ preview, status, onApprove, onReject }: HITLCardProps) {
  const rewardPreview = preview as LoyaltyRewardPreview
  const { reward, program } = rewardPreview

  return (
    <HITLCardWrapper preview={preview} status={status} onApprove={onApprove} onReject={onReject}>
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-full bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center text-amber-600 dark:text-amber-400">
          <FoodicsIcon name="card-giftcard" size={20} />
        </div>
        <div className="flex-1">
          <h4 className="font-semibold text-gray-900 dark:text-white text-lg">
            {reward.name}
          </h4>
          {program && (
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Program: {program.name || program.id}
            </p>
          )}
        </div>
      </div>

      {reward.description && (
        <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">
          {reward.description}
        </p>
      )}

      <div className="mt-3 flex flex-wrap gap-3">
        <div className="text-sm">
          <span className="text-gray-500 dark:text-gray-400">Cost: </span>
          <span className="font-semibold text-purple-600 dark:text-purple-400">
            {reward.points_cost.toLocaleString()} points
          </span>
        </div>
        {reward.value && (
          <div className="text-sm">
            <span className="text-gray-500 dark:text-gray-400">Value: </span>
            <span className="font-semibold text-green-600 dark:text-green-400">
              {formatPrice(reward.value)}
            </span>
          </div>
        )}
      </div>

      <div className="mt-2 flex gap-2">
        <span className="text-xs px-2 py-1 rounded-full bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300">
          {reward.reward_type}
        </span>
        <span className={`text-xs px-2 py-1 rounded-full ${
          reward.is_active 
            ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
            : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400'
        }`}>
          {reward.is_active ? 'Active' : 'Inactive'}
        </span>
      </div>
    </HITLCardWrapper>
  )
}

// packages/labeeb-chat/src/components/hitl/LoyaltyRewardCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { HITLPreview, HITLStatus, LoyaltyRewardPreview, Price } from '../../types/hitl-previews';
import HITLCardWrapper from './HITLCardWrapper.vue';
import { Gift, Star } from 'lucide-vue-next';

export interface LoyaltyRewardCardProps {
  preview: HITLPreview;
  status: HITLStatus;
}

const props = defineProps<LoyaltyRewardCardProps>();

const emit = defineEmits<{
  approve: [];
  reject: [reason?: string];
}>();

const rewardPreview = computed(() => props.preview as LoyaltyRewardPreview);
const reward = computed(() => rewardPreview.value.reward);
const program = computed(() => rewardPreview.value.program);

function formatPrice(price?: Price): string {
  if (!price) return '';
  return `${price.currency} ${price.amount.toLocaleString()}`;
}
</script>

<template>
  <HITLCardWrapper
    :preview="preview"
    :status="status"
    @approve="emit('approve')"
    @reject="(reason) => emit('reject', reason)"
  >
    <div class="flex items-start gap-3">
      <!-- Reward Icon -->
      <div
        class="w-12 h-12 rounded-lg bg-pink-100 dark:bg-pink-900/30 flex items-center justify-center text-pink-600 dark:text-pink-400"
      >
        <Gift :size="24" />
      </div>

      <!-- Reward Info -->
      <div class="flex-1 min-w-0">
        <h4 class="font-semibold text-gray-900 dark:text-white text-lg truncate">
          {{ reward.name }}
        </h4>
        <p v-if="reward.description" class="text-sm text-gray-600 dark:text-gray-300 mt-1">
          {{ reward.description }}
        </p>

        <!-- Points Cost -->
        <div class="flex items-center gap-2 mt-2">
          <Star :size="16" class="text-amber-500" />
          <span class="font-bold text-amber-600 dark:text-amber-400">
            {{ reward.points_cost.toLocaleString() }} points
          </span>
        </div>

        <!-- Reward Type & Value -->
        <div class="flex items-center gap-3 mt-2">
          <span class="text-xs px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400">
            {{ reward.reward_type }}
          </span>
          <span v-if="reward.value" class="text-sm font-medium text-primary-600 dark:text-primary-400">
            {{ formatPrice(reward.value) }}
          </span>
          <span
            :class="[
              'text-xs px-2 py-0.5 rounded-full',
              reward.is_active
                ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                : 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-400'
            ]"
          >
            {{ reward.is_active ? 'Active' : 'Inactive' }}
          </span>
        </div>
      </div>
    </div>

    <!-- Program Info -->
    <div v-if="program" class="mt-3 text-sm text-gray-600 dark:text-gray-400">
      <span class="font-medium">Program:</span> {{ program.name || program.id }}
    </div>
  </HITLCardWrapper>
</template>
