// react-reference/src/components/hitl/ModifierCard.tsx
import { ModifierPreview } from '../../types/hitl-previews'
import { HITLCardProps, HITLCardWrapper, formatPrice } from './HITLCard'
import { FoodicsIcon } from '../ui/FoodicsIcon'

export function ModifierCard({ preview, status, onApprove, onReject }: HITLCardProps) {
  const modifierPreview = preview as ModifierPreview
  const { modifier, product, operation } = modifierPreview

  const isAttachDetach = operation === 'attach' || operation === 'detach'

  return (
    <HITLCardWrapper preview={preview} status={status} onApprove={onApprove} onReject={onReject}>
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-full bg-teal-100 dark:bg-teal-900/30 flex items-center justify-center text-teal-600 dark:text-teal-400">
          <FoodicsIcon name="tune" size={20} />
        </div>
        <div className="flex-1">
          <h4 className="font-semibold text-gray-900 dark:text-white text-lg">
            {modifier.name}
          </h4>
          {modifier.name_localized && (
            <p className="text-sm text-gray-500 dark:text-gray-400" dir="rtl">
              {modifier.name_localized}
            </p>
          )}
          {modifier.price && (
            <p className="text-lg font-bold text-green-600 dark:text-green-400 mt-1">
              +{formatPrice(modifier.price)}
            </p>
          )}
        </div>
      </div>

      {modifier.reference && (
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">
          Reference: {modifier.reference}
        </p>
      )}

      {isAttachDetach && product && (
        <div className="mt-3 p-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700">
          <p className={`text-sm ${operation === 'attach' ? 'text-blue-600' : 'text-orange-600'}`}>
            {operation === 'attach' ? 'Attaching to:' : 'Detaching from:'}
          </p>
          <p className="font-medium text-gray-900 dark:text-white">
            {product.name || product.id}
          </p>
        </div>
      )}

      <div className="mt-2">
        <span className={`text-xs px-2 py-1 rounded-full ${
          modifier.is_active 
            ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
            : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400'
        }`}>
          {modifier.is_active ? 'Active' : 'Inactive'}
        </span>
      </div>
    </HITLCardWrapper>
  )
}

// packages/labeeb-chat/src/components/hitl/ModifierCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { HITLPreview, HITLStatus, ModifierPreview, Price } from '../../types/hitl-previews';
import HITLCardWrapper from './HITLCardWrapper.vue';
import { Settings, Package } from 'lucide-vue-next';

export interface ModifierCardProps {
  preview: HITLPreview;
  status: HITLStatus;
}

const props = defineProps<ModifierCardProps>();

const emit = defineEmits<{
  approve: [];
  reject: [reason?: string];
}>();

const modifierPreview = computed(() => props.preview as ModifierPreview);
const modifier = computed(() => modifierPreview.value.modifier);
const product = computed(() => modifierPreview.value.product);

function formatPrice(price?: Price): string {
  if (!price) return '';
  return `${price.currency} ${price.amount.toLocaleString()}`;
}
</script>

<template>
  <HITLCardWrapper
    :preview="preview"
    :status="status"
    @approve="emit('approve')"
    @reject="(reason) => emit('reject', reason)"
  >
    <div class="flex items-start gap-3">
      <!-- Modifier Icon -->
      <div
        class="w-12 h-12 rounded-lg bg-violet-100 dark:bg-violet-900/30 flex items-center justify-center text-violet-600 dark:text-violet-400"
      >
        <Settings :size="24" />
      </div>

      <!-- Modifier Info -->
      <div class="flex-1 min-w-0">
        <h4 class="font-semibold text-gray-900 dark:text-white text-lg truncate">
          {{ modifier.name }}
        </h4>
        <p v-if="modifier.reference" class="text-xs text-gray-500 dark:text-gray-400 mt-1">
          Ref: {{ modifier.reference }}
        </p>
        <p v-if="modifier.price" class="text-lg font-bold text-primary-600 dark:text-primary-400 mt-1">
          {{ formatPrice(modifier.price) }}
        </p>
        <div class="mt-2">
          <span
            :class="[
              'text-xs px-2 py-0.5 rounded-full',
              modifier.is_active
                ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                : 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-400'
            ]"
          >
            {{ modifier.is_active ? 'Active' : 'Inactive' }}
          </span>
        </div>
      </div>
    </div>

    <!-- Product Info (for attach/detach operations) -->
    <div v-if="product" class="mt-3 p-2 rounded-lg bg-gray-50 dark:bg-gray-800">
      <p class="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1 flex items-center gap-1">
        <Package :size="12" />
        Product
      </p>
      <span class="text-sm text-gray-700 dark:text-gray-300">{{ product.name || product.id }}</span>
    </div>
  </HITLCardWrapper>
</template>
