// packages/labeeb-chat/src/components/hitl/BranchCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { HITLPreview, HITLStatus, BranchPreview } from '../../types/hitl-previews';
import HITLCardWrapper from './HITLCardWrapper.vue';
import { Building2, Phone, MapPin } from 'lucide-vue-next';

export interface BranchCardProps {
  preview: HITLPreview;
  status: HITLStatus;
}

const props = defineProps<BranchCardProps>();

const emit = defineEmits<{
  approve: [];
  reject: [reason?: string];
}>();

const branchPreview = computed(() => props.preview as BranchPreview);
const branch = computed(() => branchPreview.value.branch);
</script>

<template>
  <HITLCardWrapper
    :preview="preview"
    :status="status"
    @approve="emit('approve')"
    @reject="(reason) => emit('reject', reason)"
  >
    <div class="flex items-start gap-3">
      <!-- Branch Icon -->
      <div
        class="w-12 h-12 rounded-lg bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400"
      >
        <Building2 :size="24" />
      </div>

      <!-- Branch Info -->
      <div class="flex-1 min-w-0">
        <h4 class="font-semibold text-gray-900 dark:text-white text-lg truncate">
          {{ branch.name }}
        </h4>

        <div class="space-y-1 mt-2">
          <p v-if="branch.phone" class="text-sm text-gray-600 dark:text-gray-300 flex items-center gap-2">
            <Phone :size="14" class="text-gray-400" />
            {{ branch.phone }}
          </p>
          <p v-if="branch.address" class="text-sm text-gray-600 dark:text-gray-300 flex items-center gap-2">
            <MapPin :size="14" class="text-gray-400" />
            {{ branch.address }}
          </p>
        </div>

        <div class="flex items-center gap-2 mt-2">
          <span v-if="branch.reference" class="text-xs text-gray-500 dark:text-gray-400">
            Ref: {{ branch.reference }}
          </span>
          <span
            :class="[
              'text-xs px-2 py-0.5 rounded-full',
              branch.is_active
                ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                : 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-400'
            ]"
          >
            {{ branch.is_active ? 'Active' : 'Inactive' }}
          </span>
        </div>
      </div>
    </div>
  </HITLCardWrapper>
</template>

// react-reference/src/components/hitl/BranchCard.tsx
import { BranchPreview } from '../../types/hitl-previews'
import { HITLCardProps, HITLCardWrapper } from './HITLCard'
import { FoodicsIcon } from '../ui/FoodicsIcon'

export function BranchCard({ preview, status, onApprove, onReject }: HITLCardProps) {
  const branchPreview = preview as BranchPreview
  const { branch } = branchPreview

  return (
    <HITLCardWrapper preview={preview} status={status} onApprove={onApprove} onReject={onReject}>
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-full bg-cyan-100 dark:bg-cyan-900/30 flex items-center justify-center text-cyan-600 dark:text-cyan-400">
          <FoodicsIcon name="store" size={20} />
        </div>
        <div className="flex-1">
          <h4 className="font-semibold text-gray-900 dark:text-white text-lg">
            {branch.name}
          </h4>
          {branch.name_localized && (
            <p className="text-sm text-gray-500 dark:text-gray-400" dir="rtl">
              {branch.name_localized}
            </p>
          )}
        </div>
      </div>

      <div className="mt-3 space-y-1 text-sm text-gray-600 dark:text-gray-300">
        {branch.phone && (
          <p className="flex items-center gap-2">
            <FoodicsIcon name="phone" size={14} />
            {branch.phone}
          </p>
        )}
        {branch.address && (
          <p className="flex items-start gap-2">
            <FoodicsIcon name="location-on" size={14} className="mt-0.5" />
            {branch.address}
          </p>
        )}
        {branch.reference && (
          <p className="text-gray-500 dark:text-gray-400">
            Reference: {branch.reference}
          </p>
        )}
      </div>

      <div className="mt-2">
        <span className={`text-xs px-2 py-1 rounded-full ${
          branch.is_active 
            ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
            : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400'
        }`}>
          {branch.is_active ? 'Active' : 'Inactive'}
        </span>
      </div>
    </HITLCardWrapper>
  )
}
