// packages/labeeb-chat/src/components/hitl/ComboCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { HITLPreview, HITLStatus, ComboPreview, Price } from '../../types/hitl-previews';
import HITLCardWrapper from './HITLCardWrapper.vue';
import { Layers, Package, Settings } from 'lucide-vue-next';

export interface ComboCardProps {
  preview: HITLPreview;
  status: HITLStatus;
}

const props = defineProps<ComboCardProps>();

const emit = defineEmits<{
  approve: [];
  reject: [reason?: string];
}>();

const comboPreview = computed(() => props.preview as ComboPreview);
const combo = computed(() => comboPreview.value.combo);
const product = computed(() => comboPreview.value.product);
const modifier = computed(() => comboPreview.value.modifier);

function formatPrice(price?: Price): string {
  if (!price) return '';
  return `${price.currency} ${price.amount.toLocaleString()}`;
}
</script>

<template>
  <HITLCardWrapper
    :preview="preview"
    :status="status"
    @approve="emit('approve')"
    @reject="(reason) => emit('reject', reason)"
  >
    <div class="flex items-start gap-3">
      <!-- Combo Icon -->
      <div
        class="w-12 h-12 rounded-lg bg-cyan-100 dark:bg-cyan-900/30 flex items-center justify-center text-cyan-600 dark:text-cyan-400"
      >
        <Layers :size="24" />
      </div>

      <!-- Combo Info -->
      <div class="flex-1 min-w-0">
        <h4 class="font-semibold text-gray-900 dark:text-white text-lg truncate">
          {{ combo.name || 'Combo' }}
        </h4>
        <p v-if="combo.description" class="text-sm text-gray-600 dark:text-gray-300 mt-1">
          {{ combo.description }}
        </p>
        <p v-if="combo.price" class="text-lg font-bold text-primary-600 dark:text-primary-400 mt-1">
          {{ formatPrice(combo.price) }}
        </p>
        <div class="mt-2">
          <span
            :class="[
              'text-xs px-2 py-0.5 rounded-full',
              combo.is_active
                ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                : 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-400'
            ]"
          >
            {{ combo.is_active ? 'Active' : 'Inactive' }}
          </span>
        </div>
      </div>
    </div>

    <!-- Product Info (for add_product/remove_product/update_product) -->
    <div v-if="product" class="mt-3 p-2 rounded-lg bg-gray-50 dark:bg-gray-800">
      <p class="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1 flex items-center gap-1">
        <Package :size="12" />
        Product
      </p>
      <div class="flex items-center justify-between">
        <span class="text-sm text-gray-700 dark:text-gray-300">{{ product.name || product.id }}</span>
        <div class="flex items-center gap-2">
          <span v-if="product.quantity" class="text-xs text-gray-500">
            Qty: {{ product.quantity }}
          </span>
          <span v-if="product.price" class="text-sm font-medium text-primary-600 dark:text-primary-400">
            {{ formatPrice(product.price) }}
          </span>
        </div>
      </div>
      <span
        v-if="product.is_required !== undefined"
        :class="[
          'text-xs px-2 py-0.5 rounded-full mt-1 inline-block',
          product.is_required
            ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400'
            : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400'
        ]"
      >
        {{ product.is_required ? 'Required' : 'Optional' }}
      </span>
    </div>

    <!-- Modifier Info (for add_modifier/remove_modifier) -->
    <div v-if="modifier" class="mt-3 p-2 rounded-lg bg-gray-50 dark:bg-gray-800">
      <p class="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1 flex items-center gap-1">
        <Settings :size="12" />
        Modifier
      </p>
      <div class="flex items-center justify-between">
        <span class="text-sm text-gray-700 dark:text-gray-300">{{ modifier.name || modifier.id }}</span>
        <span v-if="modifier.price" class="text-sm font-medium text-primary-600 dark:text-primary-400">
          {{ formatPrice(modifier.price) }}
        </span>
      </div>
    </div>
  </HITLCardWrapper>
</template>

// react-reference/src/components/hitl/ComboCard.tsx
import { ComboPreview } from '../../types/hitl-previews'
import { HITLCardProps, HITLCardWrapper, formatPrice } from './HITLCard'
import { FoodicsIcon } from '../ui/FoodicsIcon'

export function ComboCard({ preview, status, onApprove, onReject }: HITLCardProps) {
  const comboPreview = preview as ComboPreview
  const { combo, product, modifier, operation } = comboPreview

  return (
    <HITLCardWrapper preview={preview} status={status} onApprove={onApprove} onReject={onReject}>
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-full bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
          <FoodicsIcon name="layers" size={20} />
        </div>
        <div className="flex-1">
          <h4 className="font-semibold text-gray-900 dark:text-white text-lg">
            {combo.name || 'Combo'}
          </h4>
          {combo.description && (
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {combo.description}
            </p>
          )}
          {combo.price && (
            <p className="text-lg font-bold text-primary-600 dark:text-primary-400 mt-1">
              {formatPrice(combo.price)}
            </p>
          )}
        </div>
      </div>

      {product && (
        <div className="mt-3 p-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700">
          <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">
            {operation === 'add_product' ? 'Adding' : operation === 'remove_product' ? 'Removing' : 'Updating'}:
          </p>
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium text-gray-900 dark:text-white">
              {product.name || product.id}
            </span>
            <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300">
              {product.quantity !== undefined && (
                <span>qty: {product.quantity}</span>
              )}
              {product.price && (
                <span>{formatPrice(product.price)}</span>
              )}
            </div>
          </div>
        </div>
      )}

      {modifier && (
        <div className="mt-2 text-sm text-gray-600 dark:text-gray-300">
          <span className={operation === 'add_modifier' ? 'text-green-600' : 'text-red-600'}>
            {operation === 'add_modifier' ? 'Adding modifier:' : 'Removing modifier:'}
          </span>{' '}
          {modifier.name || modifier.id}
          {modifier.price && ` (${formatPrice(modifier.price)})`}
        </div>
      )}

      <div className="mt-2">
        <span className={`text-xs px-2 py-1 rounded-full ${
          combo.is_active 
            ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
            : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400'
        }`}>
          {combo.is_active ? 'Active' : 'Inactive'}
        </span>
      </div>
    </HITLCardWrapper>
  )
}
