// packages/labeeb-chat/src/components/hitl/SupplierCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { HITLPreview, HITLStatus, SupplierPreview, Price } from '../../types/hitl-previews';
import HITLCardWrapper from './HITLCardWrapper.vue';
import { Truck, Mail, Phone, MapPin, Package } from 'lucide-vue-next';

export interface SupplierCardProps {
  preview: HITLPreview;
  status: HITLStatus;
}

const props = defineProps<SupplierCardProps>();

const emit = defineEmits<{
  approve: [];
  reject: [reason?: string];
}>();

const supplierPreview = computed(() => props.preview as SupplierPreview);
const supplier = computed(() => supplierPreview.value.supplier);
const item = computed(() => supplierPreview.value.item);

function formatPrice(price?: Price): string {
  if (!price) return '';
  return `${price.currency} ${price.amount.toLocaleString()}`;
}
</script>

<template>
  <HITLCardWrapper
    :preview="preview"
    :status="status"
    @approve="emit('approve')"
    @reject="(reason) => emit('reject', reason)"
  >
    <div class="flex items-start gap-3">
      <!-- Supplier Icon -->
      <div
        class="w-12 h-12 rounded-lg bg-teal-100 dark:bg-teal-900/30 flex items-center justify-center text-teal-600 dark:text-teal-400"
      >
        <Truck :size="24" />
      </div>

      <!-- Supplier Info -->
      <div class="flex-1 min-w-0">
        <h4 class="font-semibold text-gray-900 dark:text-white text-lg truncate">
          {{ supplier.name }}
        </h4>

        <div class="space-y-1 mt-2">
          <p v-if="supplier.code" class="text-xs text-gray-500 dark:text-gray-400">
            Code: {{ supplier.code }}
          </p>
          <p v-if="supplier.email" class="text-sm text-gray-600 dark:text-gray-300 flex items-center gap-2">
            <Mail :size="14" class="text-gray-400" />
            {{ supplier.email }}
          </p>
          <p v-if="supplier.phone" class="text-sm text-gray-600 dark:text-gray-300 flex items-center gap-2">
            <Phone :size="14" class="text-gray-400" />
            {{ supplier.phone }}
          </p>
          <p v-if="supplier.address" class="text-sm text-gray-600 dark:text-gray-300 flex items-center gap-2">
            <MapPin :size="14" class="text-gray-400" />
            {{ supplier.address }}
          </p>
        </div>

        <div class="mt-2">
          <span
            :class="[
              'text-xs px-2 py-0.5 rounded-full',
              supplier.is_active
                ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                : 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-400'
            ]"
          >
            {{ supplier.is_active ? 'Active' : 'Inactive' }}
          </span>
        </div>
      </div>
    </div>

    <!-- Item Info (for attach/detach operations) -->
    <div v-if="item" class="mt-3 p-2 rounded-lg bg-gray-50 dark:bg-gray-800">
      <p class="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1 flex items-center gap-1">
        <Package :size="12" />
        Item
      </p>
      <div class="flex items-center justify-between">
        <span class="text-sm text-gray-700 dark:text-gray-300">{{ item.name || item.id }}</span>
        <span v-if="item.price" class="text-sm font-medium text-primary-600 dark:text-primary-400">
          {{ formatPrice(item.price) }}
        </span>
      </div>
    </div>
  </HITLCardWrapper>
</template>

// react-reference/src/components/hitl/SupplierCard.tsx
import { SupplierPreview } from '../../types/hitl-previews'
import { HITLCardProps, HITLCardWrapper, formatPrice } from './HITLCard'
import { FoodicsIcon } from '../ui/FoodicsIcon'

export function SupplierCard({ preview, status, onApprove, onReject }: HITLCardProps) {
  const supplierPreview = preview as SupplierPreview
  const { supplier, item, operation } = supplierPreview

  const isAttachDetach = operation === 'attach' || operation === 'detach'

  return (
    <HITLCardWrapper preview={preview} status={status} onApprove={onApprove} onReject={onReject}>
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-full bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
          <FoodicsIcon name="local-shipping" size={20} />
        </div>
        <div className="flex-1">
          <h4 className="font-semibold text-gray-900 dark:text-white text-lg">
            {supplier.name}
          </h4>
          {supplier.code && (
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Code: {supplier.code}
            </p>
          )}
        </div>
      </div>

      <div className="mt-3 space-y-1 text-sm text-gray-600 dark:text-gray-300">
        {supplier.email && (
          <p className="flex items-center gap-2">
            <FoodicsIcon name="mail" size={14} />
            {supplier.email}
          </p>
        )}
        {supplier.phone && (
          <p className="flex items-center gap-2">
            <FoodicsIcon name="phone" size={14} />
            {supplier.phone}
          </p>
        )}
        {supplier.address && (
          <p className="flex items-start gap-2">
            <FoodicsIcon name="location-on" size={14} className="mt-0.5" />
            {supplier.address}
          </p>
        )}
      </div>

      {isAttachDetach && item && (
        <div className="mt-3 p-2 rounded-lg bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700">
          <p className={`text-sm ${operation === 'attach' ? 'text-blue-600' : 'text-orange-600'}`}>
            {operation === 'attach' ? 'Attaching item:' : 'Detaching item:'}
          </p>
          <div className="flex items-center justify-between mt-1">
            <span className="font-medium text-gray-900 dark:text-white">
              {item.name || item.id}
            </span>
            {item.price && (
              <span className="text-sm text-gray-600 dark:text-gray-300">
                {formatPrice(item.price)}
              </span>
            )}
          </div>
        </div>
      )}

      <div className="mt-2">
        <span className={`text-xs px-2 py-1 rounded-full ${
          supplier.is_active 
            ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
            : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400'
        }`}>
          {supplier.is_active ? 'Active' : 'Inactive'}
        </span>
      </div>
    </HITLCardWrapper>
  )
}
