// react-reference/src/components/ChatSidebar.tsx
import { useState, useMemo } from 'react'
import { Session } from '../services/session-storage'
import { FoodicsIcon } from './ui/FoodicsIcon'

const INITIAL_CHATS_PER_DAY = 3

interface ChatSidebarProps {
  sessions: Session[]
  currentSessionId: string | null
  onNewSession: () => void
  onSelectSession: (sessionId: string) => void
  onDeleteSession: (sessionId: string) => void
  isCollapsed?: boolean
  onToggleCollapse?: () => void
}

interface DateSectionProps {
  dateGroup: string
  sessions: Session[]
  currentSessionId: string | null
  onSelectSession: (sessionId: string) => void
  onDeleteSession: (sessionId: string) => void
}

function DateSection({
  dateGroup,
  sessions,
  currentSessionId,
  onSelectSession,
  onDeleteSession
}: DateSectionProps) {
  const [visibleCount, setVisibleCount] = useState(INITIAL_CHATS_PER_DAY)
  const [hoveredSession, setHoveredSession] = useState<string | null>(null)

  const visibleSessions = sessions.slice(0, visibleCount)
  const hasMore = visibleCount < sessions.length
  const remainingCount = sessions.length - visibleCount
  const isExpanded = visibleCount > INITIAL_CHATS_PER_DAY

  const handleLoadMore = () => {
    setVisibleCount(prev => Math.min(prev + INITIAL_CHATS_PER_DAY, sessions.length))
  }

  const handleShowLess = () => {
    setVisibleCount(INITIAL_CHATS_PER_DAY)
  }

  return (
    <div className="mb-4">
      <div className="flex items-center gap-1.5 px-2 py-1.5 text-xs font-medium text-gray-500 dark:text-gray-400">
        <FoodicsIcon name="schedule" size={12} />
        {dateGroup}
      </div>
      <div className="space-y-1">
        {visibleSessions.map(session => (
          <div
            key={session.id}
            onMouseEnter={() => setHoveredSession(session.id)}
            onMouseLeave={() => setHoveredSession(null)}
            className={`
              group relative flex items-center gap-2 px-3 py-2 rounded-lg cursor-pointer transition-colors
              ${currentSessionId === session.id 
                ? 'bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300' 
                : 'hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300'
              }
            `}
            onClick={() => onSelectSession(session.id)}
          >
            <FoodicsIcon name="chat" size={16} className="flex-shrink-0" />
            <span className="flex-1 text-sm truncate">
              {session.title || 'New conversation'}
            </span>
            {(hoveredSession === session.id || currentSessionId === session.id) && (
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  onDeleteSession(session.id)
                }}
                className="p-1 rounded hover:bg-red-100 dark:hover:bg-red-900/30 text-gray-400 hover:text-red-600 dark:hover:text-red-400 transition-colors"
                title="Delete chat"
              >
                <FoodicsIcon name="delete" size={14} />
              </button>
            )}
          </div>
        ))}
      </div>

      {(hasMore || isExpanded) && (
        <div className="flex gap-2 mt-2">
          {hasMore && (
            <button
              onClick={handleLoadMore}
              className="flex-1 py-1.5 text-xs text-primary-600 hover:text-primary-800 dark:text-primary-400 dark:hover:text-primary-300
                         hover:bg-primary-50 dark:hover:bg-primary-900/20 rounded transition-colors flex items-center justify-center gap-1"
            >
              <FoodicsIcon name="expand-more" size={12} />
              Load More ({remainingCount} more)
            </button>
          )}
          {isExpanded && (
            <button
              onClick={handleShowLess}
              className="flex-1 py-1.5 text-xs text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300
                         hover:bg-gray-100 dark:hover:bg-gray-800 rounded transition-colors flex items-center justify-center gap-1"
            >
              <FoodicsIcon name="expand-less" size={12} />
              Show Less
            </button>
          )}
        </div>
      )}
    </div>
  )
}

export function ChatSidebar({
  sessions,
  currentSessionId,
  onNewSession,
  onSelectSession,
  onDeleteSession,
  isCollapsed = false,
  onToggleCollapse
}: ChatSidebarProps) {
  const formatDate = (date: Date | string) => {
    const now = new Date()
    const sessionDate = date instanceof Date ? date : new Date(date)
    
    if (isNaN(sessionDate.getTime())) {
      return 'Recent'
    }
    
    const diffDays = Math.floor((now.getTime() - sessionDate.getTime()) / (1000 * 60 * 60 * 24))
    
    if (diffDays === 0) {
      return 'Today'
    } else if (diffDays === 1) {
      return 'Yesterday'
    } else if (diffDays < 7) {
      return `${diffDays} days ago`
    } else {
      return sessionDate.toLocaleDateString()
    }
  }

  const groupedSessions = useMemo(() => {
    const groups: { [key: string]: Session[] } = {}
    
    sessions.forEach(session => {
      const dateKey = formatDate(session.updatedAt)
      if (!groups[dateKey]) {
        groups[dateKey] = []
      }
      groups[dateKey].push(session)
    })
    
    return groups
  }, [sessions])

  if (isCollapsed) {
    return (
      <div className="w-12 h-full bg-gray-50 dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700 flex flex-col items-center py-4">
        <button
          onClick={onToggleCollapse}
          className="p-2 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-800 text-gray-600 dark:text-gray-400 mb-4"
          title="Expand sidebar"
        >
          <FoodicsIcon name="chevron-right" size={20} />
        </button>
        <button
          onClick={onNewSession}
          className="p-2 rounded-lg bg-primary-600 text-white hover:bg-primary-700"
          title="New chat"
        >
          <FoodicsIcon name="add" size={20} />
        </button>
      </div>
    )
  }

  return (
    <div className="w-64 h-full bg-gray-50 dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700 flex flex-col">
      <div className="p-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
        <h2 className="font-semibold text-gray-900 dark:text-white">Chat History</h2>
        <button
          onClick={onToggleCollapse}
          className="p-1.5 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-800 text-gray-600 dark:text-gray-400"
          title="Collapse sidebar"
        >
          <FoodicsIcon name="chevron-left" size={16} />
        </button>
      </div>

      <div className="p-3">
        <button
          onClick={onNewSession}
          className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg bg-primary-600 text-white hover:bg-primary-700 transition-colors font-medium"
        >
          <FoodicsIcon name="add" size={16} />
          New Chat
        </button>
      </div>

      <div className="flex-1 overflow-y-auto px-2 pb-4">
        {sessions.length === 0 ? (
          <div className="text-center py-8 px-4">
            <div className="text-gray-400 mb-3 flex justify-center"><FoodicsIcon name="chat" size={40} /></div>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              No chat history yet. Start a new conversation!
            </p>
          </div>
        ) : (
          Object.entries(groupedSessions).map(([dateGroup, groupSessions]) => (
            <DateSection
              key={dateGroup}
              dateGroup={dateGroup}
              sessions={groupSessions}
              currentSessionId={currentSessionId}
              onSelectSession={onSelectSession}
              onDeleteSession={onDeleteSession}
            />
          ))
        )}
      </div>
    </div>
  )
}

// packages/labeeb-chat/src/components/ChatSidebar.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import {
  MessageSquare,
  Plus,
  Trash2,
  ChevronLeft,
  ChevronRight,
  Calendar,
  MoreVertical,
} from 'lucide-vue-next';
import { FdxButton, FdxInputText, FdxCard } from '@foodics/ui-common';
import type { Session } from '@shared/api/session-storage';

interface Props {
  sessions: Session[];
  currentSessionId: string | null;
  isCollapsed?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  isCollapsed: false,
});

const emit = defineEmits<{
  newSession: [];
  loadSession: [sessionId: string];
  deleteSession: [sessionId: string];
  toggleCollapse: [];
}>();

const searchQuery = ref('');
const sessionMenuOpen = ref<string | null>(null);

const filteredSessions = computed(() => {
  if (!searchQuery.value.trim()) {
    return props.sessions;
  }
  const query = searchQuery.value.toLowerCase();
  return props.sessions.filter(
    (session) =>
      session.title?.toLowerCase().includes(query) ||
      session.messages?.some((m) => m.content.toLowerCase().includes(query))
  );
});

const groupedSessions = computed(() => {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const yesterday = new Date(today.getTime() - 24 * 60 * 60 * 1000);
  const lastWeek = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
  const lastMonth = new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000);

  const groups: Record<string, Session[]> = {
    Today: [],
    Yesterday: [],
    'This Week': [],
    'This Month': [],
    Older: [],
  };

  filteredSessions.value.forEach((session) => {
    const sessionDate = new Date(session.updatedAt || session.createdAt);

    if (sessionDate >= today) {
      groups['Today']!.push(session);
    } else if (sessionDate >= yesterday) {
      groups['Yesterday']!.push(session);
    } else if (sessionDate >= lastWeek) {
      groups['This Week']!.push(session);
    } else if (sessionDate >= lastMonth) {
      groups['This Month']!.push(session);
    } else {
      groups['Older']!.push(session);
    }
  });

  return Object.entries(groups).filter(([, sessions]) => sessions.length > 0);
});

function formatSessionTitle(session: Session): string {
  if (session.title && session.title !== 'Untitled' && session.title !== 'New Chat') {
    return session.title.length > 30 ? session.title.slice(0, 30) + '...' : session.title;
  }
  const firstMessage = session.messages?.find((m) => m.role === 'user');
  if (firstMessage) {
    const content = firstMessage.content.trim();
    return content.length > 30 ? content.slice(0, 30) + '...' : content;
  }
  return 'New conversation';
}

function formatTime(date: Date | string): string {
  const d = new Date(date);
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function handleNewSession(): void {
  emit('newSession');
}

function handleLoadSession(sessionId: string): void {
  emit('loadSession', sessionId);
  sessionMenuOpen.value = null;
}

function handleDeleteSession(sessionId: string, event: Event): void {
  event.stopPropagation();
  emit('deleteSession', sessionId);
  sessionMenuOpen.value = null;
}

function toggleSessionMenu(sessionId: string, event: Event): void {
  event.stopPropagation();
  sessionMenuOpen.value = sessionMenuOpen.value === sessionId ? null : sessionId;
}

function handleToggleCollapse(): void {
  emit('toggleCollapse');
}
</script>

<template>
  <aside
    class="flex flex-col h-full bg-gray-50 border-r border-gray-200 transition-all duration-300"
    :class="isCollapsed ? 'w-16' : 'w-72'"
  >
    <!-- Header -->
    <div class="flex items-center justify-between p-4 border-b border-gray-200">
      <template v-if="!isCollapsed">
        <h2 class="text-lg font-semibold text-gray-900">Chat History</h2>
      </template>
      <button
        class="p-2 rounded-lg hover:bg-gray-200 text-gray-600 transition-colors"
        :title="isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'"
        @click="handleToggleCollapse"
      >
        <ChevronLeft v-if="!isCollapsed" class="w-5 h-5" />
        <ChevronRight v-else class="w-5 h-5" />
      </button>
    </div>

    <!-- New Chat Button -->
    <div class="p-3">
      <FdxButton class="w-full" :class="isCollapsed ? 'px-2' : ''" @click="handleNewSession">
        <Plus class="w-5 h-5" />
        <span v-if="!isCollapsed" class="ml-2">New Chat</span>
      </FdxButton>
    </div>

    <!-- Search -->
    <div v-if="!isCollapsed" class="px-3 pb-3">
      <FdxInputText
        v-model="searchQuery"
        placeholder="Search conversations..."
        size="sm"
      />
    </div>

    <!-- Sessions List -->
    <div class="flex-1 overflow-y-auto px-3">
      <template v-if="isCollapsed">
        <div class="space-y-2 py-2">
          <button
            v-for="session in filteredSessions.slice(0, 10)"
            :key="session.id"
            class="w-full p-2 rounded-lg transition-colors"
            :class="
              session.id === currentSessionId
                ? 'bg-primary-100 text-primary-600'
                : 'hover:bg-gray-200 text-gray-600'
            "
            :title="formatSessionTitle(session)"
            @click="handleLoadSession(session.id)"
          >
            <MessageSquare class="w-5 h-5 mx-auto" />
          </button>
        </div>
      </template>

      <template v-else>
        <div v-if="groupedSessions.length === 0" class="py-8 text-center">
          <MessageSquare class="w-12 h-12 mx-auto text-gray-300 mb-3" />
          <p class="text-sm text-gray-500">No conversations yet</p>
          <p class="text-xs text-gray-400 mt-1">Start a new chat to begin</p>
        </div>

        <div v-else class="space-y-4 pb-4">
          <div v-for="[groupName, groupSessions] in groupedSessions" :key="groupName">
            <div class="flex items-center gap-2 px-2 py-1.5">
              <Calendar class="w-3.5 h-3.5 text-gray-400" />
              <span class="text-xs font-medium text-gray-500 uppercase tracking-wider">
                {{ groupName }}
              </span>
            </div>

            <div class="space-y-1">
              <div
                v-for="session in groupSessions"
                :key="session.id"
                class="group relative rounded-lg cursor-pointer transition-colors"
                :class="
                  session.id === currentSessionId
                    ? 'bg-primary-100'
                    : 'hover:bg-gray-100'
                "
                @click="handleLoadSession(session.id)"
              >
                <div class="flex items-start gap-3 p-3">
                  <div
                    class="flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center"
                    :class="
                      session.id === currentSessionId
                        ? 'bg-primary-200 text-primary-600'
                        : 'bg-gray-200 text-gray-500'
                    "
                  >
                    <MessageSquare class="w-4 h-4" />
                  </div>
                  <div class="flex-1 min-w-0">
                    <p
                      class="text-sm font-medium truncate"
                      :class="
                        session.id === currentSessionId
                          ? 'text-primary-700'
                          : 'text-gray-900'
                      "
                    >
                      {{ formatSessionTitle(session) }}
                    </p>
                    <p class="text-xs text-gray-500 mt-0.5">
                      {{ formatTime(session.updatedAt || session.createdAt) }}
                    </p>
                  </div>

                  <button
                    class="flex-shrink-0 p-1 rounded opacity-0 group-hover:opacity-100 hover:bg-gray-200 transition-all"
                    @click="toggleSessionMenu(session.id, $event)"
                  >
                    <MoreVertical class="w-4 h-4 text-gray-500" />
                  </button>
                </div>

                <div
                  v-if="sessionMenuOpen === session.id"
                  class="absolute right-2 top-full z-10 mt-1 w-36 py-1 bg-white rounded-lg shadow-lg border border-gray-200"
                >
                  <button
                    class="w-full flex items-center gap-2 px-3 py-2 text-sm text-red-600 hover:bg-red-50"
                    @click="handleDeleteSession(session.id, $event)"
                  >
                    <Trash2 class="w-4 h-4" />
                    Delete
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </template>
    </div>
  </aside>
</template>
