// react-reference/src/pages/FoodicsDemo.tsx
import React, { useState } from 'react';
import { 
  FdxButton, 
  FdxCard, 
  FdxCardHeader, 
  FdxCardContent, 
  FdxCardFooter,
  FdxInputText,
  FdxAlert,
  FdxAvatar,
  FdxModal
} from '@/components/foodics/ui';

const FoodicsDemo: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [count, setCount] = useState(0);
  const [modalOpen, setModalOpen] = useState(false);
  const [alertVisible, setAlertVisible] = useState(true);
  const [inputValue, setInputValue] = useState('');
  const [inputError, setInputError] = useState('');

  const handleAsyncAction = async () => {
    setLoading(true);
    // Simulate async operation
    await new Promise(resolve => setTimeout(resolve, 2000));
    setLoading(false);
    setCount(prev => prev + 1);
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setInputValue(value);
    
    // Simple validation
    if (value.length < 3 && value.length > 0) {
      setInputError('Input must be at least 3 characters');
    } else {
      setInputError('');
    }
  };

  return (
    <div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-[var(--fdx-gray-900)] mb-4">
            Foodics UI Components
          </h1>
          <p className="text-lg text-[var(--fdx-gray-600)]">
            Professional React implementation of Foodics design system
          </p>
          <p className="text-sm text-[var(--fdx-gray-500)] mt-2">
            Featuring minimal design, professional color palette, and clean typography
          </p>
        </div>

        {/* Button Variants Section */}
        <div className="bg-white rounded-[var(--fdx-radius-xl)] shadow-[var(--fdx-shadow-sm)] border border-[var(--fdx-gray-200)] p-8 mb-8">
          <h2 className="text-2xl font-semibold text-[var(--fdx-gray-900)] mb-6">FdxButton Variants</h2>
          
          <div className="space-y-6">
            {/* Basic Variants */}
            <div>
              <h3 className="text-lg font-medium text-[var(--fdx-gray-700)] mb-4">Basic Variants</h3>
              <div className="flex flex-wrap gap-3">
                <FdxButton variant="default">Default</FdxButton>
                <FdxButton variant="primary">Primary</FdxButton>
                <FdxButton variant="secondary">Secondary</FdxButton>
                <FdxButton variant="danger">Danger</FdxButton>
                <FdxButton variant="link">Link</FdxButton>
                <FdxButton variant="text">Text</FdxButton>
              </div>
            </div>

            {/* Sizes */}
            <div>
              <h3 className="text-lg font-medium text-gray-700 mb-4">Sizes</h3>
              <div className="flex items-center gap-3">
                <FdxButton size="sm" variant="primary">Small</FdxButton>
                <FdxButton size="md" variant="primary">Medium</FdxButton>
                <FdxButton size="lg" variant="primary">Large</FdxButton>
              </div>
            </div>

            {/* States */}
            <div>
              <h3 className="text-lg font-medium text-gray-700 mb-4">States</h3>
              <div className="flex flex-wrap gap-3">
                <FdxButton variant="primary" disabled>Disabled</FdxButton>
                <FdxButton 
                  variant="primary" 
                  loading={loading}
                  onClick={handleAsyncAction}
                >
                  {loading ? 'Loading...' : `Clicked ${count} times`}
                </FdxButton>
              </div>
            </div>

            {/* With Icons */}
            <div>
              <h3 className="text-lg font-medium text-gray-700 mb-4">With Icons</h3>
              <div className="flex flex-wrap gap-3">
                <FdxButton 
                  variant="primary"
                  startIcon={
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                      <polyline points="7,10 12,15 17,10"/>
                      <line x1="12" y1="15" x2="12" y2="3"/>
                    </svg>
                  }
                >
                  Download
                </FdxButton>
                
                <FdxButton 
                  variant="secondary"
                  endIcon={
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M9 18l6-6-6-6"/>
                    </svg>
                  }
                >
                  Next
                </FdxButton>

                <FdxButton 
                  variant="danger"
                  startIcon={
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <polyline points="3,6 5,6 21,6"/>
                      <path d="M19,6v14a2,2,0,0,1-2,2H7a2,2,0,0,1-2-2V6m3,0V4a2,2,0,0,1,2-2h4a2,2,0,0,1,2,2V6"/>
                    </svg>
                  }
                >
                  Delete
                </FdxButton>
              </div>
            </div>
          </div>
        </div>

        {/* Interactive Example */}
        <div className="bg-white rounded-xl shadow-sm border p-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-6">Interactive Example</h2>
          
          <div className="space-y-4">
            <p className="text-gray-600">
              Click the button below to test the loading state:
            </p>
            
            <div className="flex items-center gap-4">
              <FdxButton 
                variant="primary" 
                size="lg"
                loading={loading}
                onClick={handleAsyncAction}
                startIcon={!loading ? (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
                  </svg>
                ) : undefined}
              >
                {loading ? 'Processing...' : `Awesome Action (${count})`}
              </FdxButton>
              
              <span className="text-sm text-gray-500">
                {count > 0 && `Success! Completed ${count} time${count > 1 ? 's' : ''}`}
              </span>
            </div>
          </div>
        </div>

        {/* Alert Component */}
        <div className="bg-white rounded-xl shadow-sm border p-8 mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-6">FdxAlert Component</h2>
          
          <div className="space-y-4">
            {alertVisible && (
              <FdxAlert 
                variant="info" 
                title="Information Alert"
                dismissible
                onDismiss={() => setAlertVisible(false)}
              >
                This is an informational alert that can be dismissed.
              </FdxAlert>
            )}
            
            <FdxAlert variant="success" title="Success!">
              Your action was completed successfully.
            </FdxAlert>
            
            <FdxAlert variant="warning" bordered>
              This is a warning message with borders.
            </FdxAlert>
            
            <FdxAlert variant="error" size="lg">
              This is an error alert with large size.
            </FdxAlert>

            {!alertVisible && (
              <FdxButton 
                variant="secondary" 
                size="sm"
                onClick={() => setAlertVisible(true)}
              >
                Restore Dismissed Alert
              </FdxButton>
            )}
          </div>
        </div>

        {/* Card Component */}
        <div className="bg-white rounded-xl shadow-sm border p-8 mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-6">FdxCard Component</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <FdxCard variant="default" hoverable>
              <FdxCardHeader 
                title="Default Card"
                subtitle="With hover effect"
                actions={
                  <FdxButton size="sm" variant="text">Edit</FdxButton>
                }
              />
              <FdxCardContent>
                This is a default card with some content and a hover effect.
              </FdxCardContent>
            </FdxCard>

            <FdxCard variant="bordered" clickable>
              <FdxCardHeader title="Bordered Card" />
              <FdxCardContent>
                This card has a thicker border and is clickable.
              </FdxCardContent>
              <FdxCardFooter>
                <div className="flex justify-between items-center w-full">
                  <span className="text-sm text-gray-500">Footer content</span>
                  <FdxButton size="sm" variant="primary">Action</FdxButton>
                </div>
              </FdxCardFooter>
            </FdxCard>

            <FdxCard variant="elevated" padding="lg">
              <FdxCardHeader title="Elevated Card" />
              <FdxCardContent>
                This card has a shadow elevation effect and larger padding.
              </FdxCardContent>
            </FdxCard>
          </div>
        </div>

        {/* Input Component */}
        <div className="bg-white rounded-xl shadow-sm border p-8 mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-6">FdxInputText Component</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <FdxInputText
                label="Name"
                placeholder="Enter your name"
                value={inputValue}
                onChange={handleInputChange}
                error={!!inputError}
                errorMessage={inputError}
                helpText="Minimum 3 characters required"
                required
              />
              
              <FdxInputText
                label="Email"
                type="email"
                placeholder="your@email.com"
                startIcon={
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
                    <polyline points="22,6 12,13 2,6"/>
                  </svg>
                }
              />
              
              <FdxInputText
                variant="filled"
                label="Search"
                placeholder="Search..."
                endIcon={
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <circle cx="11" cy="11" r="8"/>
                    <path d="m21 21-4.35-4.35"/>
                  </svg>
                }
              />
            </div>
            
            <div className="space-y-4">
              <FdxInputText
                variant="underlined"
                label="Underlined Input"
                placeholder="Clean underlined style"
              />
              
              <FdxInputText
                size="lg"
                placeholder="Large size input"
                disabled
                value="Disabled input"
              />
              
              <FdxInputText
                loading
                placeholder="Loading state..."
                value="Processing..."
              />
            </div>
          </div>
        </div>

        {/* Avatar Component */}
        <div className="bg-white rounded-xl shadow-sm border p-8 mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-6">FdxAvatar Component</h2>
          
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-medium text-gray-700 mb-4">Sizes</h3>
              <div className="flex items-center gap-4">
                <FdxAvatar size="xs" name="John Doe" />
                <FdxAvatar size="sm" name="Jane Smith" />
                <FdxAvatar size="md" name="Bob Wilson" />
                <FdxAvatar size="lg" name="Alice Brown" />
                <FdxAvatar size="xl" name="Charlie Davis" />
                <FdxAvatar size="2xl" name="Diana Miller" />
              </div>
            </div>

            <div>
              <h3 className="text-lg font-medium text-gray-700 mb-4">With Images</h3>
              <div className="flex items-center gap-4">
                <FdxAvatar 
                  src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face"
                  name="John Doe"
                  size="lg"
                />
                <FdxAvatar 
                  src="https://images.unsplash.com/photo-1494790108755-2616b612c5ab?w=100&h=100&fit=crop&crop=face"
                  name="Jane Smith"
                  size="lg"
                  bordered
                />
                <FdxAvatar 
                  src="invalid-url"
                  name="Fallback User"
                  size="lg"
                />
                <FdxAvatar size="lg" loading />
              </div>
            </div>

            <div>
              <h3 className="text-lg font-medium text-gray-700 mb-4">Shapes</h3>
              <div className="flex items-center gap-4">
                <FdxAvatar name="Circle" shape="circle" size="lg" />
                <FdxAvatar name="Rounded" shape="rounded" size="lg" />
                <FdxAvatar name="Square" shape="square" size="lg" />
              </div>
            </div>
          </div>
        </div>

        {/* Modal Component */}
        <div className="bg-white rounded-xl shadow-sm border p-8 mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-6">FdxModal Component</h2>
          
          <div className="flex gap-4">
            <FdxButton 
              variant="primary"
              onClick={() => setModalOpen(true)}
            >
              Open Modal
            </FdxButton>
          </div>

          <FdxModal
            open={modalOpen}
            onClose={() => setModalOpen(false)}
            title="Example Modal"
            size="lg"
            footer={
              <div className="flex gap-3">
                <FdxButton 
                  variant="secondary"
                  onClick={() => setModalOpen(false)}
                >
                  Cancel
                </FdxButton>
                <FdxButton 
                  variant="primary"
                  onClick={() => {
                    alert('Confirmed!');
                    setModalOpen(false);
                  }}
                >
                  Confirm
                </FdxButton>
              </div>
            }
          >
            <div className="space-y-4">
              <p className="text-gray-600">
                This is a modal dialog built with the FdxModal component. It supports:
              </p>
              <ul className="list-disc list-inside space-y-2 text-gray-600">
                <li>Portal rendering for proper z-index layering</li>
                <li>Backdrop click to close (configurable)</li>
                <li>Escape key to close (configurable)</li>
                <li>Multiple sizes (sm, md, lg, xl, full)</li>
                <li>Custom headers and footers</li>
                <li>Proper focus management</li>
                <li>Body scroll locking when open</li>
              </ul>
              
              <div className="mt-6">
                <FdxInputText
                  label="Test Input"
                  placeholder="You can interact with form elements"
                />
              </div>
            </div>
          </FdxModal>
        </div>

        {/* Summary */}
        <div className="bg-[var(--fdx-success-50)] rounded-[var(--fdx-radius-xl)] border border-[var(--fdx-success-200)] p-8 mt-8">
          <h2 className="text-2xl font-semibold text-[var(--fdx-success-900)] mb-4">🎉 Professional Foodics Components</h2>
          <p className="text-[var(--fdx-success-800)] mb-4">
            Successfully built professional React components with Foodics design system:
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-[var(--fdx-success-800)]">
            <ul className="space-y-2">
              <li>✅ <strong>FdxButton</strong> - Professional styling, minimal colors</li>
              <li>✅ <strong>FdxCard</strong> - Clean shadows, subtle borders</li>
              <li>✅ <strong>FdxInputText</strong> - Refined focus states, validation</li>
            </ul>
            <ul className="space-y-2">
              <li>✅ <strong>FdxAlert</strong> - Consistent status colors</li>
              <li>✅ <strong>FdxAvatar</strong> - Brand-aligned color palette</li>
              <li>✅ <strong>FdxModal</strong> - Professional backdrop, typography</li>
            </ul>
          </div>
          <p className="text-[var(--fdx-success-800)] mt-4">
            Features: Professional color system, Inter font family, CSS custom properties, minimal shadows!
          </p>
        </div>
      </div>
    </div>
  );
};

export default FoodicsDemo;

// apps/orbit/src/pages/FoodicsDemo.vue
<script setup lang="ts">
import { ref } from 'vue';
import {
  Loader2,
  CheckCircle,
  AlertTriangle,
  Info,
  XCircle,
  User,
  ChevronRight,
  Search,
  Eye,
  EyeOff,
  Mail,
  Lock,
} from 'lucide-vue-next';

const showModal = ref(false);
const loading = ref(false);
const inputValue = ref('');
const searchValue = ref('');
const emailValue = ref('');
const passwordValue = ref('');
const showPassword = ref(false);

const handleAsyncAction = async () => {
  loading.value = true;
  await new Promise((resolve) => setTimeout(resolve, 2000));
  loading.value = false;
  alert('Action completed successfully!');
};
</script>

<template>
  <div class="p-8 max-w-6xl mx-auto">
    <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-8">Foodics Design System - Vue 3</h1>

    <!-- Buttons Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Buttons</h2>

      <!-- Button Variants -->
      <div class="mb-8">
        <h3 class="text-lg font-medium text-gray-700 dark:text-gray-300 mb-4">Variants</h3>
        <div class="flex flex-wrap gap-3">
          <button class="px-4 py-2 bg-gray-100 text-gray-800 rounded-lg hover:bg-gray-200 transition-colors dark:bg-gray-700 dark:text-gray-200">
            Default
          </button>
          <button class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
            Primary
          </button>
          <button class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors">
            Secondary
          </button>
          <button class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors">
            Danger
          </button>
          <button class="px-4 py-2 text-blue-600 hover:underline transition-colors dark:text-blue-400">
            Link
          </button>
          <button class="px-4 py-2 text-gray-600 hover:text-gray-800 transition-colors dark:text-gray-400 dark:hover:text-gray-200">
            Text
          </button>
        </div>
      </div>

      <!-- Button Sizes -->
      <div class="mb-8">
        <h3 class="text-lg font-medium text-gray-700 dark:text-gray-300 mb-4">Sizes</h3>
        <div class="flex flex-wrap items-center gap-3">
          <button class="px-3 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
            Small
          </button>
          <button class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
            Medium
          </button>
          <button class="px-6 py-3 text-lg bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
            Large
          </button>
        </div>
      </div>

      <!-- Button States -->
      <div class="mb-8">
        <h3 class="text-lg font-medium text-gray-700 dark:text-gray-300 mb-4">States</h3>
        <div class="flex flex-wrap items-center gap-3">
          <button
            disabled
            class="px-4 py-2 bg-blue-600 text-white rounded-lg opacity-50 cursor-not-allowed"
          >
            Disabled
          </button>
          <button
            :disabled="loading"
            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
            @click="handleAsyncAction"
          >
            <Loader2 v-if="loading" class="w-4 h-4 animate-spin" />
            {{ loading ? 'Loading...' : 'Click Me' }}
          </button>
        </div>
      </div>

      <!-- Buttons with Icons -->
      <div class="mb-8">
        <h3 class="text-lg font-medium text-gray-700 dark:text-gray-300 mb-4">With Icons</h3>
        <div class="flex flex-wrap gap-3">
          <button class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2">
            <CheckCircle class="w-4 h-4" />
            Approve
          </button>
          <button class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors flex items-center gap-2">
            <XCircle class="w-4 h-4" />
            Reject
          </button>
          <button class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors flex items-center gap-2">
            Next
            <ChevronRight class="w-4 h-4" />
          </button>
        </div>
      </div>
    </section>

    <!-- Alerts Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Alerts</h2>
      <div class="space-y-4">
        <div class="p-4 bg-blue-50 border border-blue-200 rounded-lg flex items-start gap-3 dark:bg-blue-900/20 dark:border-blue-800">
          <Info class="w-5 h-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
          <div>
            <h4 class="font-medium text-blue-800 dark:text-blue-300">Information</h4>
            <p class="text-blue-700 dark:text-blue-400 text-sm">This is an informational alert message.</p>
          </div>
        </div>

        <div class="p-4 bg-green-50 border border-green-200 rounded-lg flex items-start gap-3 dark:bg-green-900/20 dark:border-green-800">
          <CheckCircle class="w-5 h-5 text-green-600 dark:text-green-400 flex-shrink-0 mt-0.5" />
          <div>
            <h4 class="font-medium text-green-800 dark:text-green-300">Success</h4>
            <p class="text-green-700 dark:text-green-400 text-sm">Your action was completed successfully.</p>
          </div>
        </div>

        <div class="p-4 bg-yellow-50 border border-yellow-200 rounded-lg flex items-start gap-3 dark:bg-yellow-900/20 dark:border-yellow-800">
          <AlertTriangle class="w-5 h-5 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
          <div>
            <h4 class="font-medium text-yellow-800 dark:text-yellow-300">Warning</h4>
            <p class="text-yellow-700 dark:text-yellow-400 text-sm">Please review this before continuing.</p>
          </div>
        </div>

        <div class="p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3 dark:bg-red-900/20 dark:border-red-800">
          <XCircle class="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
          <div>
            <h4 class="font-medium text-red-800 dark:text-red-300">Error</h4>
            <p class="text-red-700 dark:text-red-400 text-sm">Something went wrong. Please try again.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Cards Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Cards</h2>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div class="p-6 bg-white dark:bg-gray-800 rounded-xl">
          <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-2">Default Card</h3>
          <p class="text-gray-600 dark:text-gray-400">This is a basic card with no border.</p>
        </div>

        <div class="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
          <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-2">Bordered Card</h3>
          <p class="text-gray-600 dark:text-gray-400">This card has a subtle border.</p>
        </div>

        <div class="p-6 bg-white dark:bg-gray-800 rounded-xl shadow-lg">
          <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-2">Elevated Card</h3>
          <p class="text-gray-600 dark:text-gray-400">This card has a shadow elevation.</p>
        </div>
      </div>
    </section>

    <!-- Input Fields Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Input Fields</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Default Input</label>
          <input
            v-model="inputValue"
            type="text"
            placeholder="Enter text..."
            class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">With Icon</label>
          <div class="relative">
            <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              v-model="searchValue"
              type="text"
              placeholder="Search..."
              class="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Email Input</label>
          <div class="relative">
            <Mail class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              v-model="emailValue"
              type="email"
              placeholder="email@example.com"
              class="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Password Input</label>
          <div class="relative">
            <Lock class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              v-model="passwordValue"
              :type="showPassword ? 'text' : 'password'"
              placeholder="Enter password"
              class="w-full pl-10 pr-10 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            <button
              type="button"
              class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
              @click="showPassword = !showPassword"
            >
              <EyeOff v-if="showPassword" class="w-4 h-4" />
              <Eye v-else class="w-4 h-4" />
            </button>
          </div>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Disabled Input</label>
          <input
            type="text"
            placeholder="Disabled"
            disabled
            class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400 cursor-not-allowed"
          />
        </div>

        <div>
          <label class="block text-sm font-medium text-red-600 dark:text-red-400 mb-2">Error State</label>
          <input
            type="text"
            placeholder="Invalid input"
            class="w-full px-4 py-2 border border-red-500 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-red-500 focus:border-transparent"
          />
          <p class="mt-1 text-sm text-red-600 dark:text-red-400">This field is required</p>
        </div>
      </div>
    </section>

    <!-- Avatars Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Avatars</h2>
      <div class="flex flex-wrap items-end gap-4">
        <div class="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white text-sm font-medium">
          SM
        </div>
        <div class="w-10 h-10 rounded-full bg-green-600 flex items-center justify-center text-white font-medium">
          MD
        </div>
        <div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center text-white font-medium">
          LG
        </div>
        <div class="w-16 h-16 rounded-full bg-orange-600 flex items-center justify-center text-white text-lg font-medium">
          XL
        </div>
        <div class="w-12 h-12 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
          <User class="w-6 h-6 text-gray-500 dark:text-gray-400" />
        </div>
      </div>
    </section>

    <!-- Modal Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Modal</h2>
      <button
        class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        @click="showModal = true"
      >
        Open Modal
      </button>

      <!-- Modal Overlay -->
      <Teleport to="body">
        <div
          v-if="showModal"
          class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
          @click.self="showModal = false"
        >
          <div class="bg-white dark:bg-gray-800 rounded-xl p-6 max-w-md w-full mx-4 shadow-xl">
            <h3 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">Modal Title</h3>
            <p class="text-gray-600 dark:text-gray-400 mb-6">
              This is a modal dialog. You can put any content here including forms, images, or other components.
            </p>
            <div class="flex justify-end gap-3">
              <button
                class="px-4 py-2 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
                @click="showModal = false"
              >
                Cancel
              </button>
              <button
                class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                @click="showModal = false"
              >
                Confirm
              </button>
            </div>
          </div>
        </div>
      </Teleport>
    </section>

    <!-- Badges Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Badges</h2>
      <div class="flex flex-wrap gap-3">
        <span class="px-2 py-1 bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded text-sm font-medium">
          Default
        </span>
        <span class="px-2 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-300 rounded text-sm font-medium">
          Primary
        </span>
        <span class="px-2 py-1 bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300 rounded text-sm font-medium">
          Success
        </span>
        <span class="px-2 py-1 bg-yellow-100 dark:bg-yellow-900/30 text-yellow-800 dark:text-yellow-300 rounded text-sm font-medium">
          Warning
        </span>
        <span class="px-2 py-1 bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300 rounded text-sm font-medium">
          Danger
        </span>
        <span class="px-2 py-1 bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-300 rounded text-sm font-medium">
          Info
        </span>
      </div>
    </section>

    <!-- Progress Section -->
    <section class="mb-12">
      <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-6">Progress Bars</h2>
      <div class="space-y-4">
        <div>
          <div class="flex justify-between mb-1">
            <span class="text-sm text-gray-600 dark:text-gray-400">Progress</span>
            <span class="text-sm text-gray-600 dark:text-gray-400">25%</span>
          </div>
          <div class="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
            <div class="bg-blue-600 h-2 rounded-full" style="width: 25%"></div>
          </div>
        </div>

        <div>
          <div class="flex justify-between mb-1">
            <span class="text-sm text-gray-600 dark:text-gray-400">Progress</span>
            <span class="text-sm text-gray-600 dark:text-gray-400">50%</span>
          </div>
          <div class="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
            <div class="bg-green-600 h-2 rounded-full" style="width: 50%"></div>
          </div>
        </div>

        <div>
          <div class="flex justify-between mb-1">
            <span class="text-sm text-gray-600 dark:text-gray-400">Progress</span>
            <span class="text-sm text-gray-600 dark:text-gray-400">75%</span>
          </div>
          <div class="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
            <div class="bg-yellow-500 h-2 rounded-full" style="width: 75%"></div>
          </div>
        </div>

        <div>
          <div class="flex justify-between mb-1">
            <span class="text-sm text-gray-600 dark:text-gray-400">Progress</span>
            <span class="text-sm text-gray-600 dark:text-gray-400">100%</span>
          </div>
          <div class="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
            <div class="bg-green-600 h-2 rounded-full" style="width: 100%"></div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
